package body Tackle.MIME is
   function Init return Database is
   begin
      return (Data => [
         --  Web / Markup
         "css" => "text/css",
         "dtd" => "application/xml-dtd",
         "htm" => "text/html",
         "html" => "text/html",
         "js" => "text/javascript",
         "json" => "application/json",
         "jsonld" => "application/ld+json",
         "mjs" => "text/javascript",
         "xhtml" => "application/xhtml+xml",
         "xml" => "application/xml",
         "xsl" => "application/xml",
         "xslt" => "application/xslt+xml",

         --  Text / Config / Data
         "cfg" => "text/plain",
         "conf" => "text/plain",
         "csv" => "text/csv",
         "diff" => "text/x-diff",
         "geojson" => "application/geo+json",
         "ics" => "text/calendar",
         "ini" => "text/plain",
         "log" => "text/plain",
         "markdown" => "text/markdown",
         "md" => "text/markdown",
         "ndjson" => "application/x-ndjson",
         "patch" => "text/x-diff",
         "rtf" => "application/rtf",
         "text" => "text/plain",
         "toml" => "application/toml",
         "tsv" => "text/tab-separated-values",
         "txt" => "text/plain",
         "vcard" => "text/vcard",
         "vcf" => "text/vcard",
         "yaml" => "application/yaml",
         "yml" => "application/yaml",

         --  Documents
         "ai" => "application/postscript",
         "bib" => "text/x-bibtex",
         "djv" => "image/vnd.djvu",
         "djvu" => "image/vnd.djvu",
         "doc" => "application/msword",
         "docx" => "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
         "dot" => "application/msword",
         "dotx" => "application/vnd.openxmlformats-officedocument.wordprocessingml.template",
         "eps" => "application/postscript",
         "epub" => "application/epub+zip",
         "latex" => "application/x-latex",
         "mobi" => "application/x-mobipocket-ebook",
         "odf" => "application/vnd.oasis.opendocument.formula",
         "odg" => "application/vnd.oasis.opendocument.graphics",
         "odp" => "application/vnd.oasis.opendocument.presentation",
         "ods" => "application/vnd.oasis.opendocument.spreadsheet",
         "odt" => "application/vnd.oasis.opendocument.text",
         "pdf" => "application/pdf",
         "ppt" => "application/vnd.ms-powerpoint",
         "pptx" => "application/vnd.openxmlformats-officedocument.presentationml.presentation",
         "ps" => "application/postscript",
         "tex" => "application/x-tex",
         "xls" => "application/vnd.ms-excel",
         "xlsm" => "application/vnd.ms-excel.sheet.macroEnabled.12",
         "xlsx" => "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",

         --  Images
         "apng" => "image/apng",
         "avif" => "image/avif",
         "bmp" => "image/bmp",
         "cr2" => "image/x-canon-cr2",
         "gif" => "image/gif",
         "heic" => "image/heic",
         "heif" => "image/heif",
         "ico" => "image/x-icon",
         "jpe" => "image/jpeg",
         "jpeg" => "image/jpeg",
         "jpg" => "image/jpeg",
         "jxl" => "image/jxl",
         "nef" => "image/x-nikon-nef",
         "pbm" => "image/x-portable-bitmap",
         "pgm" => "image/x-portable-graymap",
         "png" => "image/png",
         "ppm" => "image/x-portable-pixmap",
         "psd" => "image/vnd.adobe.photoshop",
         "raw" => "image/x-raw",
         "svg" => "image/svg+xml",
         "svgz" => "image/svg+xml",
         "tif" => "image/tiff",
         "tiff" => "image/tiff",
         "webp" => "image/webp",
         "xbm" => "image/x-xbitmap",
         "xpm" => "image/x-xpixmap",

         --  Audio
         "aac" => "audio/aac",
         "aif" => "audio/aiff",
         "aiff" => "audio/aiff",
         "au" => "audio/basic",
         "flac" => "audio/flac",
         "m4a" => "audio/mp4",
         "mid" => "audio/midi",
         "midi" => "audio/midi",
         "mp3" => "audio/mpeg",
         "oga" => "audio/ogg",
         "ogg" => "audio/ogg",
         "opus" => "audio/opus",
         "ra" => "audio/x-realaudio",
         "snd" => "audio/basic",
         "wav" => "audio/wav",
         "weba" => "audio/webm",
         "wma" => "audio/x-ms-wma",

         --  Video
         "3g2" => "video/3gpp2",
         "3gp" => "video/3gpp",
         "avi" => "video/x-msvideo",
         "flv" => "video/x-flv",
         "m4v" => "video/mp4",
         "mkv" => "video/x-matroska",
         "mov" => "video/quicktime",
         "mp4" => "video/mp4",
         "mpe" => "video/mpeg",
         "mpeg" => "video/mpeg",
         "mpg" => "video/mpeg",
         "ogv" => "video/ogg",
         "qt" => "video/quicktime",
         "ts" => "video/mp2t",
         "webm" => "video/webm",
         "wmv" => "video/x-ms-wmv",

         --  Archives / Disk Images
         "7z" => "application/x-7z-compressed",
         "ar" => "application/x-archive",
         "bz2" => "application/x-bzip2",
         "cab" => "application/vnd.ms-cab-compressed",
         "cpio" => "application/x-cpio",
         "dmg" => "application/x-apple-diskimage",
         "gz" => "application/gzip",
         "gzip" => "application/gzip",
         "img" => "application/x-raw-disk-image",
         "iso" => "application/x-iso9660-image",
         "lz" => "application/x-lzip",
         "lz4" => "application/x-lz4",
         "lzma" => "application/x-lzma",
         "rar" => "application/vnd.rar",
         "tar" => "application/x-tar",
         "tgz" => "application/x-tar",
         "xz" => "application/x-xz",
         "zip" => "application/zip",
         "zst" => "application/zstd",

         --  Packages / System
         "apk" => "application/vnd.android.package-archive",
         "bat" => "application/x-msdos-program",
         "com" => "application/x-msdos-program",
         "csh" => "application/x-csh",
         "deb" => "application/vnd.debian.binary-package",
         "msi" => "application/x-msi",
         "rpm" => "application/x-rpm",
         "sh" => "application/x-sh",

         --  Fonts
         "eot" => "application/vnd.ms-fontobject",
         "otf" => "font/otf",
         "ttf" => "font/ttf",
         "woff" => "font/woff",
         "woff2" => "font/woff2",

         --  Binaries / Executables
         "a" => "application/x-archive",
         "bin" => "application/octet-stream",
         "class" => "application/java-vm",
         "dll" => "application/octet-stream",
         "dylib" => "application/octet-stream",
         "exe" => "application/octet-stream",
         "jar" => "application/java-archive",
         "o" => "application/octet-stream",
         "so" => "application/octet-stream",
         "war" => "application/java-archive",
         "wasm" => "application/wasm",

         --  Programming Languages
         "ada" => "text/x-ada",
         "adb" => "text/x-ada",
         "ads" => "text/x-ada",
         "asm" => "text/x-asm",
         "c" => "text/x-c",
         "cc" => "text/x-c++src",
         "clj" => "text/x-clojure",
         "cmake" => "text/x-cmake",
         "coffee" => "text/coffeescript",
         "cpp" => "text/x-c++src",
         "cs" => "text/x-csharp",
         "cxx" => "text/x-c++src",
         "d" => "text/x-d",
         "dart" => "text/x-dart",
         "ejs" => "application/x-ejs",
         "el" => "text/x-emacs-lisp",
         "elm" => "text/x-elm",
         "erb" => "application/x-erb",
         "erl" => "text/x-erlang",
         "ex" => "text/x-elixir",
         "f90" => "text/x-fortran",
         "f95" => "text/x-fortran",
         "fs" => "text/x-fsharp",
         "go" => "text/x-go",
         "graphql" => "application/graphql",
         "groovy" => "text/x-groovy",
         "h" => "text/x-c",
         "hh" => "text/x-c++hdr",
         "hpp" => "text/x-c++hdr",
         "hs" => "text/x-haskell",
         "java" => "text/x-java-source",
         "jl" => "text/x-julia",
         "jsp" => "text/x-jsp",
         "jsx" => "text/x-jsx",
         "kt" => "text/x-kotlin",
         "less" => "text/x-less",
         "lisp" => "text/x-common-lisp",
         "lua" => "text/x-lua",
         "m" => "text/x-objcsrc",
         "makefile" => "text/x-makefile",
         "ml" => "text/x-ocaml",
         "nim" => "text/x-nim",
         "nix" => "text/x-nix",
         "pas" => "text/x-pascal",
         "php" => "application/x-httpd-php",
         "pl" => "text/x-perl",
         "pm" => "text/x-perl",
         "pp" => "text/x-pascal",
         "proto" => "text/x-protobuf",
         "ps1" => "text/x-powershell",
         "purs" => "text/x-purescript",
         "py" => "text/x-python",
         "r" => "text/x-r",
         "rb" => "text/x-ruby",
         "rkt" => "text/x-racket",
         "rs" => "text/x-rust",
         "s" => "text/x-asm",
         "sass" => "text/x-sass",
         "scala" => "text/x-scala",
         "scm" => "text/x-scheme",
         "scss" => "text/x-scss",
         "sql" => "application/sql",
         "svelte" => "text/x-svelte",
         "swift" => "text/x-swift",
         "tcl" => "text/x-tcl",
         "tsx" => "text/x-typescript-jsx",
         "v" => "text/x-v",
         "vala" => "text/x-vala",
         "vue" => "text/x-vue",
         "zig" => "text/x-zig",

         --  Feeds / Geo
         "atom" => "application/atom+xml",
         "gpx" => "application/gpx+xml",
         "kml" => "application/vnd.google-earth.kml+xml",
         "kmz" => "application/vnd.google-earth.kmz",
         "opml" => "text/x-opml",
         "rss" => "application/rss+xml",

         --  Email / Messaging
         "eml" => "message/rfc822",
         "mbox" => "application/mbox",
         "msg" => "application/vnd.ms-outlook",

         --  Databases
         "db" => "application/x-database",
         "dbf" => "application/x-dbf",
         "sqlite" => "application/vnd.sqlite3",

         --  Certificates / Crypto
         "asc" => "application/pgp-encrypted",
         "cer" => "application/pkix-cert",
         "crt" => "application/x-x509-ca-cert",
         "csr" => "application/pkcs10",
         "gpg" => "application/gpg-keys",
         "key" => "application/x-pem-file",
         "p12" => "application/x-pkcs12",
         "pem" => "application/x-pem-file",
         "pfx" => "application/x-pkcs12",
         "sig" => "application/pgp-signature",

         --  3D Models
         "3ds" => "application/x-3ds",
         "dae" => "model/vnd.collada+xml",
         "fbx" => "application/x-fbx",
         "glb" => "model/gltf-binary",
         "gltf" => "model/gltf+json",
         "obj" => "model/obj",
         "stl" => "model/stl",

         --  Gemini
         "gemini" => "text/gemini",
         "gmi" => "text/gemini",

         --  Legacy / Other
         "swf" => "application/x-shockwave-flash"]);
   end Init;

   function Mime_Type (Self : Database; Extension : String; Default : String := "") return String is
      use Extension_To_Mime_Type_Maps;

      C : constant Cursor := Self.Data.Find (Extension);
   begin
      if Has_Element (C) then
         return Element (C);
      else
         return Default;
      end if;
   end Mime_Type;
end Tackle.MIME;
